pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'aryandhuri/Q5-node-app'
        DOCKER_TAG = 'latest'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/Artistlenc1234/P5Q5.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh '/usr/local/bin/docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop old container if exists
                    sh '/usr/local/bin/docker rm -f Q5-node-app || true'

                    // Run new container
                    sh '/usr/local/bin/docker run -d -p 3000:3000 --name Q5-node-app $DOCKER_IMAGE:$DOCKER_TAG'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment complete! App is running.'
        }
        failure {
            echo '❌ Something went wrong during the pipeline.'
        }
    }
}
